// Response from https://content-youtube.googleapis.com/youtube/v3/playlistItems?playlistId=OLAK5uy_lVHKpWYVeLJEP2eqMjfCk0uYE54qRXo10&maxResults=50&part=contentDetails%2Cid%2Csnippet%2Cstatus&key=AIzaSyAa8yy0GdcGPHdtD083HiGGx_S0vMPScDM

const response = {
  "kind": "youtube#playlistItemListResponse",
  "etag": "OlXS_VhHXCUF7dva8dYTY4HwCao",
  "items": [
    {
      "kind": "youtube#playlistItem",
      "etag": "Bk82WivhrcU7VXe9qv5pvNIKm-w",
      "id": "T0xBSzV1eV9sVkhLcFdZVmVMSkVQMmVxTWpmQ2swdVlFNTRxUlhvMTAuMTNGMkFGMUE4OTk4MkNGOQ",
      "snippet": {
        "publishedAt": "2023-09-29T03:18:04Z",
        "channelId": "UCBR8-60-B28hp2BmDPdntcQ",
        "title": "Boat Buds",
        "description": "Provided to YouTube by CDBaby\n\nBoat Buds · Mark Sparling\n\nBoat Buds: A Short Hike EP\n\n℗ 2021 Mark Sparling\n\nReleased on: 2021-01-18\n\nAuto-generated by YouTube.",
        "thumbnails": {
          "default": {
            "url": "https://i.ytimg.com/vi/Dc30Pk_Ib1w/default.jpg",
            "width": 120,
            "height": 90
          },
          "medium": {
            "url": "https://i.ytimg.com/vi/Dc30Pk_Ib1w/mqdefault.jpg",
            "width": 320,
            "height": 180
          },
          "high": {
            "url": "https://i.ytimg.com/vi/Dc30Pk_Ib1w/hqdefault.jpg",
            "width": 480,
            "height": 360
          },
          "standard": {
            "url": "https://i.ytimg.com/vi/Dc30Pk_Ib1w/sddefault.jpg",
            "width": 640,
            "height": 480
          },
          "maxres": {
            "url": "https://i.ytimg.com/vi/Dc30Pk_Ib1w/maxresdefault.jpg",
            "width": 1280,
            "height": 720
          }
        },
        "channelTitle": "YouTube",
        "playlistId": "OLAK5uy_lVHKpWYVeLJEP2eqMjfCk0uYE54qRXo10",
        "position": 0,
        "resourceId": {
          "kind": "youtube#video",
          "videoId": "Dc30Pk_Ib1w"
        },
        "videoOwnerChannelTitle": "Mark Sparling - Topic",
        "videoOwnerChannelId": "UCPw7S3ZvjuPnc2-KCIxZYbw"
      },
      "contentDetails": {
        "videoId": "Dc30Pk_Ib1w",
        "videoPublishedAt": "2021-01-17T10:06:03Z"
      },
      "status": {
        "privacyStatus": "public"
      }
    },
    {
      "kind": "youtube#playlistItem",
      "etag": "FjY6T7mux9Qjmj06xifbrYFeT_4",
      "id": "T0xBSzV1eV9sVkhLcFdZVmVMSkVQMmVxTWpmQ2swdVlFNTRxUlhvMTAuMkI3Q0VEMkNDNDBGQkJBMQ",
      "snippet": {
        "publishedAt": "2023-09-29T03:18:04Z",
        "channelId": "UCBR8-60-B28hp2BmDPdntcQ",
        "title": "Beach Buds (Flight Mix)",
        "description": "Provided to YouTube by CDBaby\n\nBeach Buds (Flight Mix) · Mark Sparling\n\nBoat Buds: A Short Hike EP\n\n℗ 2021 Mark Sparling\n\nReleased on: 2021-01-18\n\nAuto-generated by YouTube.",
        "thumbnails": {
          "default": {
            "url": "https://i.ytimg.com/vi/c5CxLUwJATw/default.jpg",
            "width": 120,
            "height": 90
          },
          "medium": {
            "url": "https://i.ytimg.com/vi/c5CxLUwJATw/mqdefault.jpg",
            "width": 320,
            "height": 180
          },
          "high": {
            "url": "https://i.ytimg.com/vi/c5CxLUwJATw/hqdefault.jpg",
            "width": 480,
            "height": 360
          },
          "standard": {
            "url": "https://i.ytimg.com/vi/c5CxLUwJATw/sddefault.jpg",
            "width": 640,
            "height": 480
          },
          "maxres": {
            "url": "https://i.ytimg.com/vi/c5CxLUwJATw/maxresdefault.jpg",
            "width": 1280,
            "height": 720
          }
        },
        "channelTitle": "YouTube",
        "playlistId": "OLAK5uy_lVHKpWYVeLJEP2eqMjfCk0uYE54qRXo10",
        "position": 1,
        "resourceId": {
          "kind": "youtube#video",
          "videoId": "c5CxLUwJATw"
        },
        "videoOwnerChannelTitle": "Mark Sparling - Topic",
        "videoOwnerChannelId": "UCPw7S3ZvjuPnc2-KCIxZYbw"
      },
      "contentDetails": {
        "videoId": "c5CxLUwJATw",
        "videoPublishedAt": "2021-01-17T10:04:25Z"
      },
      "status": {
        "privacyStatus": "public"
      }
    },
    {
      "kind": "youtube#playlistItem",
      "etag": "EKUNTRtzv2kV9zqfbEHf3MhAR_g",
      "id": "T0xBSzV1eV9sVkhLcFdZVmVMSkVQMmVxTWpmQ2swdVlFNTRxUlhvMTAuRUZCMzZCRUJEN0ZFMDlGOQ",
      "snippet": {
        "publishedAt": "2023-09-29T03:18:04Z",
        "channelId": "UCBR8-60-B28hp2BmDPdntcQ",
        "title": "Somewhere in the Woods (Flight Mix)",
        "description": "Provided to YouTube by CDBaby\n\nSomewhere in the Woods (Flight Mix) · Mark Sparling\n\nBoat Buds: A Short Hike EP\n\n℗ 2021 Mark Sparling\n\nReleased on: 2021-01-18\n\nAuto-generated by YouTube.",
        "thumbnails": {
          "default": {
            "url": "https://i.ytimg.com/vi/Ezl0eDxazeY/default.jpg",
            "width": 120,
            "height": 90
          },
          "medium": {
            "url": "https://i.ytimg.com/vi/Ezl0eDxazeY/mqdefault.jpg",
            "width": 320,
            "height": 180
          },
          "high": {
            "url": "https://i.ytimg.com/vi/Ezl0eDxazeY/hqdefault.jpg",
            "width": 480,
            "height": 360
          },
          "standard": {
            "url": "https://i.ytimg.com/vi/Ezl0eDxazeY/sddefault.jpg",
            "width": 640,
            "height": 480
          },
          "maxres": {
            "url": "https://i.ytimg.com/vi/Ezl0eDxazeY/maxresdefault.jpg",
            "width": 1280,
            "height": 720
          }
        },
        "channelTitle": "YouTube",
        "playlistId": "OLAK5uy_lVHKpWYVeLJEP2eqMjfCk0uYE54qRXo10",
        "position": 2,
        "resourceId": {
          "kind": "youtube#video",
          "videoId": "Ezl0eDxazeY"
        },
        "videoOwnerChannelTitle": "Mark Sparling - Topic",
        "videoOwnerChannelId": "UCPw7S3ZvjuPnc2-KCIxZYbw"
      },
      "contentDetails": {
        "videoId": "Ezl0eDxazeY",
        "videoPublishedAt": "2021-01-17T10:04:25Z"
      },
      "status": {
        "privacyStatus": "public"
      }
    },
    {
      "kind": "youtube#playlistItem",
      "etag": "N3cI8yb_wTYS8uIGt29oCUFQ1Sg",
      "id": "T0xBSzV1eV9sVkhLcFdZVmVMSkVQMmVxTWpmQ2swdVlFNTRxUlhvMTAuNDNGODBFQzNDMUU2MURERA",
      "snippet": {
        "publishedAt": "2023-09-29T03:18:04Z",
        "channelId": "UCBR8-60-B28hp2BmDPdntcQ",
        "title": "See You at the Top (Flight Mix)",
        "description": "Provided to YouTube by CDBaby\n\nSee You at the Top (Flight Mix) · Mark Sparling\n\nBoat Buds: A Short Hike EP\n\n℗ 2021 Mark Sparling\n\nReleased on: 2021-01-18\n\nAuto-generated by YouTube.",
        "thumbnails": {
          "default": {
            "url": "https://i.ytimg.com/vi/BJNkEeZezSw/default.jpg",
            "width": 120,
            "height": 90
          },
          "medium": {
            "url": "https://i.ytimg.com/vi/BJNkEeZezSw/mqdefault.jpg",
            "width": 320,
            "height": 180
          },
          "high": {
            "url": "https://i.ytimg.com/vi/BJNkEeZezSw/hqdefault.jpg",
            "width": 480,
            "height": 360
          },
          "standard": {
            "url": "https://i.ytimg.com/vi/BJNkEeZezSw/sddefault.jpg",
            "width": 640,
            "height": 480
          },
          "maxres": {
            "url": "https://i.ytimg.com/vi/BJNkEeZezSw/maxresdefault.jpg",
            "width": 1280,
            "height": 720
          }
        },
        "channelTitle": "YouTube",
        "playlistId": "OLAK5uy_lVHKpWYVeLJEP2eqMjfCk0uYE54qRXo10",
        "position": 3,
        "resourceId": {
          "kind": "youtube#video",
          "videoId": "BJNkEeZezSw"
        },
        "videoOwnerChannelTitle": "Mark Sparling - Topic",
        "videoOwnerChannelId": "UCPw7S3ZvjuPnc2-KCIxZYbw"
      },
      "contentDetails": {
        "videoId": "BJNkEeZezSw",
        "videoPublishedAt": "2021-01-17T10:04:25Z"
      },
      "status": {
        "privacyStatus": "public"
      }
    },
    {
      "kind": "youtube#playlistItem",
      "etag": "AbKB4j6nV_vYoEmtMLMAvTFbRpA",
      "id": "T0xBSzV1eV9sVkhLcFdZVmVMSkVQMmVxTWpmQ2swdVlFNTRxUlhvMTAuODhCNzVENEE5RTNBQjlFOA",
      "snippet": {
        "publishedAt": "2023-09-29T03:18:04Z",
        "channelId": "UCBR8-60-B28hp2BmDPdntcQ",
        "title": "Boat Buds (Alternate Mix)",
        "description": "Provided to YouTube by CDBaby\n\nBoat Buds (Alternate Mix) · Mark Sparling\n\nBoat Buds: A Short Hike EP\n\n℗ 2021 Mark Sparling\n\nReleased on: 2021-01-18\n\nAuto-generated by YouTube.",
        "thumbnails": {
          "default": {
            "url": "https://i.ytimg.com/vi/TnsmKZmw_QY/default.jpg",
            "width": 120,
            "height": 90
          },
          "medium": {
            "url": "https://i.ytimg.com/vi/TnsmKZmw_QY/mqdefault.jpg",
            "width": 320,
            "height": 180
          },
          "high": {
            "url": "https://i.ytimg.com/vi/TnsmKZmw_QY/hqdefault.jpg",
            "width": 480,
            "height": 360
          },
          "standard": {
            "url": "https://i.ytimg.com/vi/TnsmKZmw_QY/sddefault.jpg",
            "width": 640,
            "height": 480
          },
          "maxres": {
            "url": "https://i.ytimg.com/vi/TnsmKZmw_QY/maxresdefault.jpg",
            "width": 1280,
            "height": 720
          }
        },
        "channelTitle": "YouTube",
        "playlistId": "OLAK5uy_lVHKpWYVeLJEP2eqMjfCk0uYE54qRXo10",
        "position": 4,
        "resourceId": {
          "kind": "youtube#video",
          "videoId": "TnsmKZmw_QY"
        },
        "videoOwnerChannelTitle": "Mark Sparling - Topic",
        "videoOwnerChannelId": "UCPw7S3ZvjuPnc2-KCIxZYbw"
      },
      "contentDetails": {
        "videoId": "TnsmKZmw_QY",
        "videoPublishedAt": "2021-01-17T10:04:24Z"
      },
      "status": {
        "privacyStatus": "public"
      }
    }
  ],
  "pageInfo": {
    "totalResults": 5,
    "resultsPerPage": 50
  }
};

export default response;